### ISSUE TITLE
[cPP CHANGE] FCS_STG_EXT.2 & 3

### ISSUE THREAD

**Issue by robertmclemons** [DSC-iTC/cPP#153]
FCS_STG_EXT.2 refers to FCS_COP.1/KeyEnc, which is no longer a thing.

I've been trying to figure out a way to get rid of FCS_STG_EXT.2 & 3 and replace them with FCS_CKM_EXT.3. I haven't quite gotten there, but I suggest the following change:

FCS_STG_EXT.2.1. The TSF shall encrypt [AKs, SKs, KEKs, and [selection: long-term trusted channel key material, all software-based key storage, no other keys]] using one of the following methods: [selection: key encapsulation, key wrapping].

There are a couple problems:
At this point key wrapping does not include GCM and CCM modes, but maybe the CWG will include them. This would also eliminate the need for FCS_STG_EXT.3, since all those methods provide integrity as well as confidentiality.

The other problem is that the old FCS_COP.1/KeyEnc allows "encryption" through XOR of a key with a KEK. This isn't allowed by the new catalog. Nor does it provide integrity. It would make things a lot simpler if we could get rid of  XOR because then all the allowed methods would include integrity and we could get rid of STG_EXT.3.

**Comment by woodbe** [comment]
I think we may be able to use FCS_CKM_EXT.3 from the catalog for this and possibly remove FCS_STG_EXT.2 & 3.

> FCS_CKM_EXT.3.1 The TSF shall use specified cryptographic key access methods [selection: key encapsulation, key wrapping, key encryption] that meets the following: [selection: list of standards] to access keys when performing [selection: cryptographic key usage in cryptographic operations, cryptographic key archival, cryptographic key backup, cryptographic key escrow, cryptographic key recovery, modifications to attributes of cryptographic keys, cryptographic key destruction].

In this I would adjust the "list of standards" to say "list of standards that provide integrity and confidentiality" or something like that, which would restrict the "encryption" options to things like GCM.

We could also adjust this to change "to access keys" after that second selection to be "to access keys and [selection: long-term trusted channel key material, all software-based key storage, no other keys]".

**Comment by woodbe** [comment]
Related, could "long-term trusted channel key material" be the same thing as "persistent secrets" that are in FCS_STG_EXT.1.1? It isn't clear this is the case anywhere as persistent secrets aren't defined (nor are long-term trusted channel key material). A long term material would seem to be persistent (persistent doesn't mean permanent).

If this is the case, then this further simplifies the way to tweak these SFRs by simplifying the terms and expectations.

**Comment by robertmclemons** [comment]
I guess "long term trusted key material" could include public keys where integrity is important but not confidentiality, while "secrets" generally require both. Not sure the distinction matters.

Anyway, I think it would be pretty clean if we can use FCS_STG_EXT.1 for storing key-things in the TOE and FCS_CKM.3 or FCS_CKM_EXT.3 for storing them outside the TOE.

**Comment by woodbe** [comment]
Yes, that or if they selected "software storage". Maybe we should add another selection to the list of things that this is used for, so that could be a little more clear.

**Comment by woodbe** [comment]
@robertmclemons if the user had mutable hardware-based protected storage, it seems to me that we have an assumption that the DSC may not encrypt the stored keys. This would be what we did with the #150 dependency where if hardware-based is what is used then the expectation is that FPT_PHP.3 protects the SDEs and not encryption (not that someone couldn't do both, of course).

As such, it would seem that FCS_CKM_EXT.3 is actually selection-based.

So FCS_STG_EXT.1.1 has the vendor specify hardware or software protected storage. If they use software, then FCS_CKM_EXT.3 is brought in. Depending on the selection of how keys are protected in FCS_CKM_EXT.3, then FCS_COP.1/KeyEncap or FCS_COP.1/KeyWrap would be brought in (or neither if something like AES-GCM is used since that would come from FCS_COP.1/SKC).

Now the question for FCS_STG_EXT.3 is whether all those methods of integrity need to be allowed. They are all encryption of some sort, but 2 of them use separate hashes and the last one does a KAT with the decrypted key. 

Now I could see those 3 things as being accepted as "list of standards that provide integrity and confidentiality" and add them to the app note to clarify those as accepted.

What do you think of this linkage? This makes the most sense to me at this point.

**Comment by woodbe** [comment]
Also, the new FCS_CKM.3 dependency in CC:2022 would make this a dependency instead (since it is a modification of that SFR) to resolve those concerns. Again though, like in #150, I think we can state that this is a dependency when using software storage but when using hardware storage that FPT_PHP.3 satisfies the dependency.

**Comment by smuellerDD** [comment]
There must be an allowance that some secret key material is not wrapped/encrypted/encapsulated. Every DSC does have some secret key material that is stored in plaintext, but protected by physical means. This key material is at least one part of the root of trust of the entire key hierarchy. For the keys other than those hardware-protected ones, I see the key material must be subject to wrapping/encapsulation/encryption.

Yet, I do not see that always an authenticating cipher must be used. It would be permissible if a key is encrypted (no authentication) and that key in turn is used eventually to unwrap another key with an authenticating cipher. I.e. the encrypted key is just another step to get to THE actual key you want to protect. For example, such "just encrypted" key may bring in the property of being replay protected. In this case, you do not need its integrity as integrity is checked at one later stage. I am not sure that this can be meaningfully described in the PP, thus I would simply like to lean on the CWG result and simply use the FCS_CKM_EXT.3 from them verbatim.

**Comment by woodbe** [comment]
Notes:

- Move CCM/GCM from FCS_COP.1/SKC to FCS_COP.1/KeyWrap
- App note about allowing hash/hmac with CBC (or similar)
- figure out whether or not the last FCS_STG_EXT.3.1 option with the KAT should still be included or if it can be removed in the update
- Remove FCS_STG_EXT.2/3

**Comment by woodbe** [comment]
Note about @smuellerDD comment. The expectation is that the vendor is careful about what the define as keys so they don't call something that could be used as a key in a process which doesn't require it to be stored as a key in the key hierarchy a "key" but something else (like token). This is intended for protection the keys.

**Comment by smuellerDD** [comment]
Agreed.

**Comment by robertmclemons** [comment]
-> Move CCM/GCM from FCS_COP.1/SKC to FCS_COP.1/KeyWrap

I would copy them rather than move them so the TOE can use CCM and GCM for things other than wrapping keys.

**Comment by woodbe** [comment]
I can see that, but then do we really want it duplicated? Maybe leave that part alone (leave it in SKC) and then just add a note in the Key encryption description below that CCM/GCM are also acceptable along with say CBC + hash.

That may be the best way as it doesn't clutter duplicate options around. The sentence already states the CBC + hash type of things, so also having CCM/GCM there do not seem like a problem.

I can make that update later (before the call).

**Comment by woodbe** [comment]
The main issue with the TRRT thing is that we already have that as an approved method today, so it would be taking it away, which I don't think would be acceptable. We could flesh out the SFR selections though to make it more explicit, which could help the automation.

I have copied the CCM/GCM back into the original locations so now those features are in both. I am inclined though to think that maybe they aren't needed in the KeyWrap since we need to have the CBC option.
