### ISSUE TITLE
Introduction SDEs/SDOs description

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#179]
encryption of secret keys is advised but there is nothing said to decryption process where and how this process can occur and if there is s.th. or someone that who could decrypt those apparently important keys in case of eventual problems or missing conditions for decryption. This is elementary information particularly for root key use case.

**Comment by slpotte** [comment]
It's not clear which section we are talking here.  

In section 2.2.4 we list security attributes for SDOs.  Although I like this concept, I was not comfortable with enumerating a list of security attributes for a couple of reasons.  1) we cannot list all possible security attributes, 2) we shouldn't mandate a list of security attributes since different contexts will have different security requirements.  But, I'm happy to leave this list as an example, and even happier if we annotate as an example.

I found NIST SP 800-152, Section 6.2.1 "Metadata Elements" under Section 6.2 "Key Metadata".  The Security Attributes can be mapped the Key Metadata, even though not all SDO are keys:
SDO.ID -> 6.2.1.b Key Identifier
SDO.Type -> 6.2.1.l Key Type
SDO.AuthData -> 6.2.1.s.iv [non-crypt trust process for key protection]
SDO.ReAuth -> 6.2.1.t.iv [non-crypt trust process for metadata protection]
SDO.Conf -> 6.1 [cryptographic key]
SDO.Export -> 6.2.1.n [key security policy] and 6.2.1.s.ii [non-crypt trust process for key protection]
SDO.Integrity -> 6.2.1.s.i [key integrity]
SDO.Bind ->  6.2.1.n [key security policy] and 6.2.1.s.ii [non-crypt trust process for key protection]

The NIST document has a lot of nice options in section 6.2.1 for SDO security attribute "metadata".  I'm open to referencing this document without copying it contents into the cPP.

As for SDOs for which confidentiality is called for, then anytime a private key (in the case of asymmetric cryptographic algorithms), or secret key (in the case of symmetric cryptographic algorithms) is used to encrypt or decrypt the protected element (which we are calling the SDE to distinguish it from the other security attributes/metadata of the SDO), then those operations should only be carried out within the confines of an approved DSC.  

Perhaps we add the following wording to the assumption A.TRUSTED_PEER:  Hosts to the DSC and client applications are assumed to be trustworthy and will not transfer private keys (in the case of asymmetric cryptographic algorithms) or secret key (in the case of symmetric cryptographic algorithms) to unauthorized or untrustworthy entities.

There are certain root keys (private or secret) which cannot be encrypted since they may exist in a boot environment in which it's not possible to supply the necessary key to decrypt it.  I'm not sure that we need to say a lot about this unless we are prepared to levy hardware requirements for protected cleartext keys.

The second paragraph of section 2.4.6 talks about SDOs with wrapped keys; encryption is implied here.  This cPP sets up mechanisms to encrypt objects such as keys before exporting from the DSC, as well as setting up encrypted channels in those cases in which keys are to be transported without wrapping.  Ultimately, the security policy set up with the key when it was provisioned determines whether or not to wrap it before exporting or transporting; the DSC should honor those security policies.

**Comment by woodbe** [comment]
OK, so the initial question here, as I see it, is more about what is meant by the various SDEs and SDOs. I think the confusion comes into play when it is stated that root keys are administrator keys. This is true in a sense, but I don't think it is the right way to put this. There are RoT keys and other root keys (best example would probably be a hardware-fused encryption key, but could also encompass say a fused hash for a digital signature to verify firmware) which may be used by the DSC, but which aren't tied to authentication as they are the underlying keys of the system (on which all the security may be built). Some of these would be used internally regardless of the role as they are how the system works. 

So from that standpoint I think that stating things about root keys should be taken out the description. Even the diagram itself shows root keys being separate from the authorization, so I think this just confuses things.

@slpotte the rest of the point about changing the SFR is valid, I don't know if it is a priority right now, but it could be done as a separate topic.

**Comment by slpotte** [comment]
Which section?

**Comment by woodbe** [comment]
Section 2.4.4, 

https://github.com/DSC-iTC/cPP/blob/e1cb23c5e74585d10b155a6d427b9e10376a708a/cPP_DSC.adoc?plain=1#L338

**Comment by slpotte** [comment]
So the action is:

Remove "Root keys installed by the manufacturers are considered administrator key material." from the middle of the second paragraph.  

I saw nothing about SDOs and SDEs in section 2.4.4.
