### ISSUE TITLE
FPT_PRO_EXT.1 multiple roots?

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#198]
can there be more than one in a system? If so please precise. This should not be the case usually. Otherwise ROT could not be afterwards determined and or used and there cannot be drawn any benefit from its existence.

**Comment by slpotte** [comment]
FPT_PRO_EXT.1.1 is specific to the identity of the Root of Trust.  With the migration from classical to post-quantum/quantum-resistant algorithms, we are going to see multiple identities for the same Root of Trust in the form of a key.  If we make a change, I would advocate for "The TSF shall contain [strikethrough "an", add "at least one"] SDO that contains the identity of the Root of Trust. 

These SFRs neither prohibit nor promote multiple roots of trust.  Let's not "fix" that.

**Comment by woodbe** [comment]
So does this really mean that we have multiple RoTs, or just that it can provide proof in different ways based on the needs of the calling thing (so it can provide PQC if needed or classic elsewhere)?

The main thing though is that if the intro says "single", then the description and the requirements don't match, so we should be clear in the intro, since currently that is actually setting expectations there can only be a single RoT. Personally while I understand the goal of a single RoT, a phone probably has multiple, really, coming from different components. Some may be the same (like a TEE may provide the RoT used by the device as a whole), but others may be unique to that component (say one in an eSE if there is one). So I'm not sure there is really a point to forcing a single RoT, even within the DSC, but if that is the case, then the intro should be tweaked to make that clear. Of course does that end up meaning we need to explain why you may have multiple, or can we just make some small tweaks to remove the "single"?

@slpotte do you have any thoughts about what we may want to change in the intro to not set expectations that we are precluding multiple RoTs?

**Comment by slpotte** [comment]
@woodbe, This SFR is specific to the identity of a RoT, which implies that the RoT provides some sort of authentication or verification service.  RoTs that provide measurement or storage services need not have an identity.   In the context of a DSC, I'm assuming there is only one set of firmware that boots/initializes the DSC, which constitutes the "primary" RoT along with keys or "identity" values.   I'm also assuming that the DSC provides RoT services to the rest of the device (not the DSC, but the thing hosting the DSC) in which it is embedded.  The identity may be a private or secret key used to create signatures so that entities remote to the DSC can authenticate whatever the DSC is signing.  The number of RoTs is not very relevant in this process.  Thursday morning I will ponder your question on whether or not we really want to change the intro.

**Comment by slpotte** [comment]
Every DSC is expected to have [delete: a single, add: at least one] RoT that comprises the DSC hardware and pre-installed SDOs, from which services (e.g. Storage, Authorization, etc.) can be offered.

**Comment by woodbe** [comment]
Change "one root of trust" to "a root of trust"
