### ISSUE TITLE
atsec/2 - Section 6.7.8 - FPT_STM.1 to Selection-based

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#2]
FPT_STM.1

### Comment:
FPT_STM.1 states that the TSF shall be able to provide reliable timestamps.  Application Note 41 states that it is acceptable for the TSF to provide timestamp data either through an internal clock or a counter or to obtain it from a clock contained within the same physical enclosure as the TOE.  Table 12 "SFR-Objective Rationale" in section 6.9 of DSC cPP points out two scenarios where the TOE makes use of time: 1) to determine when excessive authentication failure attempts have been made. 2) as input to cryptographic functions.  It is clear that the way FPT_STM.1 is written in the PP, the TOE is expected to either provide the timestamp itself or obtain it from the operational environment. However, there may be cases where the TOE doesn't  use time in the two scenarios above or the TOE doesn't need to use time at all then FPT_STM.1 cannot be fulfilled. Also, Table 18 "SFR Dependencies Rationale for Mandatory SFRs" of the PP doesn't list FPT_STM.1 as a dependency to any other SFR. Therefore, would be more appropriate for FPT_STM.1 as selection-based rather than mandatory.

### Proposal:
Make FPT_STM.1 a selection-based SFR. If FPT_STM.1 is selected, the timestamp can either provided by the TOE or TOE OE.

### Priority: 2

**Comment by woodbe** [comment]
@yiatsec this makes sense, but is it required for the immediate evaluation or could this wait until v1.1?

**Comment by yiatsec** [comment]
@woodbe We need a TD for the immediate evaluation stating that the timestamps may be provided by the TOE OE as an acceptable interpretation for "within the same physical enclosure as the TOE." Changing it to a selection-based SFR can wait until v1.1.

**Comment by woodbe** [comment]
@yiatsec  Please provide a proposed TD for the interpretation (not the move to selection-based). I do not think that this requires a TD as I think that the physical enclosure encompasses everything inside the physical device.

The only thing I could think that could make this more clear would be to state that the physical enclosure is the device the TOE is embedded inside. So for example changing Application Note 41 to something along the lines of:

> It is acceptable for the TSF to provide timestamp data either through an internal clock or a counter. It is also permissible for the TSF to obtain time data from a clock contained within the same physical enclosure **in which the TOE is embedded (for example a mobile device)**.

The bold is added to make it clear that the enclosure is the "final product".

**Comment by woodbe** [comment]
Consider doing this as a change to the TSS evidence in the SD instead.

**Comment by woodbe** [comment]
Proposed change:

Location: SD - section 2.5.7.1.1

Add the following paragraphs (after the existing paragraph, # 414)

>The evaluator shall examine the TSS and other vendor documentation and ensure they describe the location of the time source for the TSF.

> [conditional] For a time source that is outside the TOE but contained inside the same enclosure, the evaluator shall ensure there is a description of how the time is obtained from the source outside the TOE.

**Comment by jfisherbah** [comment]
I agree that proposed interpretation is valid based on app note 41, and that the proposed update to the evaluation activity is suitable.

For future versions of the PP we should consider either adding a [TOE, platform] selection to the SFR (which may or may not force us to redefine it as extended, I think other PPs have just added those to Part 2 SFRs via refinement though), or keeping it as-is but making it implementation-based (assuming that construction exists in cPPs). 

I don't think selection-based works because we'd need a trigger for it, and making a stub SFR for "The TSF shall use a [selection: internal, external] time source" just makes it feel like we're using two SFRs to do what can be covered by one.

**Comment by yiatsec** [comment]
The current Table 18 "SFR Dependencies Rationale for Mandatory SFRs" doesn't list FPT_STM.1 as a dependency to any other SFR, so a TOE may not need a time stamp at all. If you add a stub SFR to mandate FPT_STM.1, then Table 18 needs to be updated to reflect the new SFR.

**Comment by jfisherbah** [comment]
It's unclear to me how we should list the dependencies when the dependency only applies part of the time. In the case of FPT_STM.1, it is a dependency on FIA_AFL_EXT.1.3 but only when one of the two selections related to time are chosen. It is also potentially a dependency on FMT_MSA.3 if time data is applied to the SDO.Reauth attribute. Both of those SFRs could have listed FPT_STM.1 as a dependency but I think it would be confusing to do that because neither of them are defined in such a way where time data is *always* needed.

With respect to FPT_STM.1 potentially being selection-based, I would agree if FIA_AFL_EXT.1 is the only potential use of time, because there are selections in that SFR that could then force FPT_STM.1 to be included. But since FMT_MSA.3 may also need it, independent of any selections in the SFR, we may need to classify it some other way.

Also, we have FPT_STM.1 mapped to O.STRONG_CRYPTO but I'm not actually sure whether that should stay there - do we have any cryptographic functions in the PP that would require a time value to function? Maybe we don't and then that mapping could be removed.

**Comment by woodbe** [comment]
While I can agree with cleaning up dependency tables, in this case, do we feel that is necessary to fully accomplish what we need here? At the moment this is attempting to just make sure that a time source outside the TOE is explicitly acceptable, while changing dependencies seems like it would tie into some broader update that we should tackle as part of v1.1 (and if so, create a new issue specifically for that).

**Comment by woodbe** [comment]
Agreement on call for this TD. @woodbe will create a proposed TD for final vote.

**Comment by jfisherbah** [comment]
I don't think anything related to the disposition of FPT_STM.1 is needed to address the issue at hand. This can be opened as a separate issue if desired. Concur with TD being created for vote.

**Comment by woodbe** [comment]
https://github.com/DSC-iTC/DSC-iTC.github.io/pull/3
