### ISSUE TITLE
Hidden throttling requirement in FIA_SOS.2 SD

### ISSUE THREAD

**Issue by woodbe** [DSC-iTC/cPP#273]
https://github.com/DSC-iTC/cPP/blob/cbeef0306a44ab3af99352404baff9b6a8124f8b/SD_DSC.adoc?plain=1#L1516

In this line we have a requirement that throttling be implemented. This is not in the SFR, nor is it anywhere else in the cPP at this point (the only things we had discussed regarding throttling were all removed as they were related to the PBKDF functions).

I think this line should be removed, but am proposing it as an issue before creating the PR.

**Comment by woodbe** [comment]
Check with CC:2022 just in case, otherwise this can be removed.

**Comment by woodbe** [comment]
OK, I looked at the SFR again, and actually think that the real issue here is the the second line in the SFR is the problem. It is laying out a requirement on the generation of the secret that it can't be guessed within 1 minute. That is throttling, but is not really something that this SFR actually specifies. Looking at the CC definition of the SFR, the first bullet looks good, but the second one seems to be laying out constraints that are not appropriate for this SFR. And given that we already removed throttling as a specific claim, I think actually we should remove that bullet and the line in the SD.

**Comment by slpotte** [comment]
I don't recall why the term "authorization data" is used in FIA_SOS.2, nor in the rest of the cPP.  Authorization data is the unique term used in full disk encryption (FDE) which is a 256-bit value that is randomly generated and then encrypted.  When decrypted/revealed, it is used to authorize the decryption of a volume/disk of data.  In order to reveal the authorization data, one must authenticate oneself to gain access to it.  

The original intent of FIA_SOS.2 was to generate authentication secrets, such as PINs and passwords, something that a person knows.  Throttling in this context is the act of preventing a user from manually (or automatically) entering unlimited guesses for authentication secrets into the physical TOE.  However, I believe there were other SFRs to deal with this sort of throttling.  This is limited to authentication and does not apply to PBKDFs.

Furthermore, switching tracks back to authorization data, authorization data in this PP has a very broad definition.  It includes typical authentication values such as PINs and passwords as well as 256-bit FDE values that are randomly generated.  If authorization data are used in the derivation or generation of an encryption key, then this SFR should NOT apply; in these cases, PBKDF SFRs apply.

The second bullet is curious.  It conflicts with the first one: 1 success in 100,000 vs 1,000,000 guesses.  The second bullet doesn't make sense for those cases in which the authorization data is a 256-bit secret value which is not meant to be entered manually into the TOE by a user.  The one-minute time limit would make sense in the context of user entry of authorization data such as PINs and passwords, but what should we make of the value 100,000?  Do we really expect a user to enter 100,000 PINs per second?

This SFR should be restricted to user-entered authorization data such as PINs and passwords and not to the 256-bit randomly generated values found in the FDE cPP.

**Comment by woodbe** [comment]
This is related to #127
