### ISSUE TITLE
[cPP PUBLIC REVIEW] [atsec08] FDP_SDC.2 EA

### ISSUE THREAD

**Issue by jvdsn** [DSC-iTC/cPP#372]
In its evaluation activities, FDP_SDC.2 makes references to selections from the SFR text:

> If the TSF stores this data inside the TOE boundary, the evaluator shall ensure that TSF **uses one of the listed methods** to provide confidentiality

> In this case, use the evaluation activities of the FPT_PHP.3 if [.underline]#protected storage# is selected, FCS_COP.1/SKC if [.underline]#symmetric encryption using…# is selected, and FCS_COP.1/KeyWrap if [.underline]#key wrapping using…# is selected.

However, FDP_SDC.2 does not define any selections. It seemingly does not specify how the actual protection must occur.

**Comment by woodbe** [comment]
OK, I'm looking at some of the linkage here, and seeing that it should probably run through FCS_STG_EXT.1.1, but we have limited that to just "keys" and "persistent secrets", but I think that probably has to be broader. Maybe that FCS_STG_EXT.1 should really be broken up, one about the type of storage, one about what you can do in it.

The simple, shorter answer right now may be to just add "SDEs" to the list of things that should be protected, I don't know (but is this a selection, or is it mandatory?). I have a starting point on this, but think this is something that probably needs to be re-evalauted again with v3.

**Comment by jvdsn** [comment]
> This would be a hidden requirement (and was such in the v1.0 as there was no reference to FDP_ETC_EXT.2 in the SFR).

I do think FDP_ETC_EXT.2 makes sense though, but maybe there's no reason for it to be referenced here. FDP_ETC_EXT.2 stands on its own, saying that SDOs must be wrapped to be exported.

**Comment by woodbe** [comment]
I agree that it stands on its own, but the way this is written, as an app note, but like it is a requirement, makes it look somewhat hidden. For example, in that SFR, you could say that "make sure you wrap the data according to FCS_COP.1/KeyWrap" or something like that. This is not really saying anything extra, but if you do it like that it looks like you are layering on an additional requirement (especially since in this particular case the SFR is not mandatory). The general rule is that the app note should explain the SFR and how to use/complete it. If it needs to reference another SFR, then that should be explicit in the SFR (like when we say to use key wrapping as defined in FCS_COP.1/KeyWrap).
